/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.util.Date;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author January
 */
public class Register extends javax.swing.JFrame {
    private ButtonGroup buttonGroup = new ButtonGroup();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelBackground = new javax.swing.JPanel();
        jPanelSignUp = new javax.swing.JPanel();
        jLbSignUp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldTelophone = new javax.swing.JTextField();
        jTfFirstName = new javax.swing.JTextField();
        jLbLastName = new javax.swing.JLabel();
        jLbDateOfBirth = new javax.swing.JLabel();
        jLabelStarLN = new javax.swing.JLabel();
        jLbId = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jLbGender = new javax.swing.JLabel();
        jLbPassWord = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLbFirstName = new javax.swing.JLabel();
        jLbStarId = new javax.swing.JLabel();
        jLbStarFirstName = new javax.swing.JLabel();
        jLbStarGender = new javax.swing.JLabel();
        jLbStarBirthDay = new javax.swing.JLabel();
        jLbStarPassword = new javax.swing.JLabel();
        jLbPosition = new javax.swing.JLabel();
        jLbStarPosition = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLbCongenitialDisease = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLbTelophone = new javax.swing.JLabel();
        jLbStarTelophone = new javax.swing.JLabel();
        jTextFieldConDisease = new javax.swing.JTextField();
        jLbEmail = new javax.swing.JLabel();
        jLbStarEmail = new javax.swing.JLabel();
        jPasswordSignUp = new javax.swing.JPasswordField();
        jPasswordConfirmPassSignup = new javax.swing.JPasswordField();
        jLbConfirmPassWord = new javax.swing.JLabel();
        jLbStarConfirmPass = new javax.swing.JLabel();
        jDateChooserBirthDate = new com.toedter.calendar.JDateChooser();
        jButtonSignUp = new javax.swing.JButton();
        jRadioButtonGenderFemale = new javax.swing.JRadioButton();
        jRadioButtonGenderMale = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBackground.setPreferredSize(new java.awt.Dimension(940, 540));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSignUp.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbSignUp.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLbSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jLbSignUp.setText("SignUp");
        jPanelSignUp.add(jLbSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 195, 50));
        jPanelSignUp.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 640, 20));

        jTextFieldTelophone.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldTelophone.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jTextFieldTelophone.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTelophone.setText("090xxxxxxx");
        jTextFieldTelophone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldTelophone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTelophoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelophoneFocusLost(evt);
            }
        });
        jTextFieldTelophone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelophoneActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldTelophone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 230, 30));

        jTfFirstName.setBackground(new java.awt.Color(0, 0, 0));
        jTfFirstName.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jTfFirstName.setForeground(new java.awt.Color(102, 102, 102));
        jTfFirstName.setText("Name");
        jTfFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTfFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfFirstNameFocusLost(evt);
            }
        });
        jTfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFirstNameActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTfFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 230, 30));

        jLbLastName.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLbLastName.setText("LastName");
        jPanelSignUp.add(jLbLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 60, 20));

        jLbDateOfBirth.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbDateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        jLbDateOfBirth.setText("Date of Birth");
        jPanelSignUp.add(jLbDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, 20));

        jLabelStarLN.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabelStarLN.setForeground(new java.awt.Color(0, 204, 204));
        jLabelStarLN.setText("*");
        jLabelStarLN.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLabelStarLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 30, 30));

        jLbId.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbId.setForeground(new java.awt.Color(255, 255, 255));
        jLbId.setText("ID");
        jPanelSignUp.add(jLbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 20, 20));

        jComboBoxPosition.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxPosition.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jComboBoxPosition.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "นักศึกษา ", "อาจารย์และบุคลากร ", "ช่าง ", "เจ้าหน้าที่" }));
        jComboBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPositionActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jComboBoxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 230, 30));

        jLbGender.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbGender.setForeground(new java.awt.Color(255, 255, 255));
        jLbGender.setText("Gender");
        jPanelSignUp.add(jLbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 20));

        jLbPassWord.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbPassWord.setForeground(new java.awt.Color(255, 255, 255));
        jLbPassWord.setText("Password");
        jPanelSignUp.add(jLbPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 50, 20));

        jTextFieldSurname.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldSurname.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jTextFieldSurname.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldSurname.setText("Surname");
        jTextFieldSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSurnameFocusLost(evt);
            }
        });
        jTextFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSurnameActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 230, 30));

        jLbFirstName.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbFirstName.setForeground(new java.awt.Color(255, 255, 255));
        jLbFirstName.setText("FirstName");
        jPanelSignUp.add(jLbFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));

        jLbStarId.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarId.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarId.setText("*");
        jLbStarId.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 30, 30));

        jLbStarFirstName.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarFirstName.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarFirstName.setText("*");
        jLbStarFirstName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, 30));

        jLbStarGender.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarGender.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarGender.setText("*");
        jLbStarGender.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 30, 30));

        jLbStarBirthDay.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarBirthDay.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarBirthDay.setText("*");
        jLbStarBirthDay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarBirthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 30, 30));

        jLbStarPassword.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarPassword.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarPassword.setText("*");
        jLbStarPassword.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 30, 30));

        jLbPosition.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbPosition.setForeground(new java.awt.Color(255, 255, 255));
        jLbPosition.setText("Position");
        jPanelSignUp.add(jLbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 50, 20));

        jLbStarPosition.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarPosition.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarPosition.setText("*");
        jLbStarPosition.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 30, 30));

        jTextFieldId.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldId.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("591305000XX");
        jTextFieldId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIdFocusLost(evt);
            }
        });
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 230, 30));

        jLbCongenitialDisease.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbCongenitialDisease.setForeground(new java.awt.Color(255, 255, 255));
        jLbCongenitialDisease.setText("Congenitial Disease");
        jPanelSignUp.add(jLbCongenitialDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, 20));

        jTextFieldEmail.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setText("aaaa@gmail.com");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 530, 30));

        jLbTelophone.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbTelophone.setForeground(new java.awt.Color(255, 255, 255));
        jLbTelophone.setText("Telophone");
        jPanelSignUp.add(jLbTelophone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 60, 20));

        jLbStarTelophone.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarTelophone.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarTelophone.setText("*");
        jLbStarTelophone.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarTelophone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 30, 30));

        jTextFieldConDisease.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldConDisease.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldConDisease.setText("ถ้ามี");
        jTextFieldConDisease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextFieldConDisease.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldConDiseaseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldConDiseaseFocusLost(evt);
            }
        });
        jTextFieldConDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConDiseaseActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldConDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 230, 30));

        jLbEmail.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLbEmail.setText("E-Mail");
        jPanelSignUp.add(jLbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 40, 20));

        jLbStarEmail.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarEmail.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarEmail.setText("*");
        jLbStarEmail.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 30, 30));

        jPasswordSignUp.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordSignUp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordSignUp.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordSignUp.setText("jPasswordField1");
        jPasswordSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPasswordSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordSignUpFocusLost(evt);
            }
        });
        jPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordSignUpActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jPasswordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 230, 30));

        jPasswordConfirmPassSignup.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordConfirmPassSignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordConfirmPassSignup.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordConfirmPassSignup.setText("jPasswordField1");
        jPasswordConfirmPassSignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPasswordConfirmPassSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordConfirmPassSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordConfirmPassSignupFocusLost(evt);
            }
        });
        jPanelSignUp.add(jPasswordConfirmPassSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 230, 30));

        jLbConfirmPassWord.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbConfirmPassWord.setForeground(new java.awt.Color(255, 255, 255));
        jLbConfirmPassWord.setText("Comfirm Password");
        jPanelSignUp.add(jLbConfirmPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 100, 20));

        jLbStarConfirmPass.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLbStarConfirmPass.setForeground(new java.awt.Color(0, 204, 204));
        jLbStarConfirmPass.setText("*");
        jLbStarConfirmPass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelSignUp.add(jLbStarConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 30, 30));

        jDateChooserBirthDate.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooserBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSignUp.add(jDateChooserBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 230, 30));

        jButtonSignUp.setBackground(new java.awt.Color(0, 255, 255));
        jButtonSignUp.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSignUp.setText("SIGN UP");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jButtonSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 80, -1));

        jRadioButtonGenderFemale.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonGenderFemale.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jRadioButtonGenderFemale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonGenderFemale.setText("Female");
        jRadioButtonGenderFemale.setDisplayedMnemonicIndex(0);
        jPanelSignUp.add(jRadioButtonGenderFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, -1));

        jRadioButtonGenderMale.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonGenderMale.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jRadioButtonGenderMale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonGenderMale.setText("Male");
        jRadioButtonGenderMale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonGenderMaleFocusGained(evt);
            }
        });
        jRadioButtonGenderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGenderMaleActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jRadioButtonGenderMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jPanelBackground.add(jPanelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 680, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\January\\Documents\\NetBeansProjects\\Project\\icon\\backgroung.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanelBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelophoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelophoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelophoneActionPerformed

    private void jTfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFirstNameActionPerformed

    private void jComboBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPositionActionPerformed

    private void jTextFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSurnameActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldConDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConDiseaseActionPerformed

    private void jPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordSignUpActionPerformed

    private void jTfFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfFirstNameFocusGained
        // เมื่อคลิกให้ Name เป็นเป็นว่างเปล่า
        jTfFirstName.setText(" ");
        jTfFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTfFirstNameFocusGained

    private void jTextFieldSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSurnameFocusGained
        // TODO add your handling code here:
        jTextFieldSurname.setText(" ");
        jTextFieldSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTextFieldSurnameFocusGained

    private void jTextFieldSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSurnameFocusLost
        // TODO add your handling code here:
        jTextFieldSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTextFieldSurnameFocusLost

    private void jTfFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfFirstNameFocusLost
        // TODO add your handling code here:
        jTfFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTfFirstNameFocusLost

    private void jTextFieldIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIdFocusGained
        // TODO add your handling code here:
        jTextFieldId.setText(" ");
        jTextFieldId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTextFieldIdFocusGained

    private void jTextFieldIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIdFocusLost
        // TODO add your handling code here:
        jTextFieldId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTextFieldIdFocusLost

    private void jTextFieldConDiseaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldConDiseaseFocusGained
        // TODO add your handling code here:
        jTextFieldConDisease.setText(" ");
        jTextFieldConDisease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTextFieldConDiseaseFocusGained

    private void jTextFieldConDiseaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldConDiseaseFocusLost
        // TODO add your handling code here:
        jTextFieldConDisease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTextFieldConDiseaseFocusLost

    private void jTextFieldTelophoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelophoneFocusGained
        // TODO add your handling code here:
        jTextFieldTelophone.setText(" ");
        jTextFieldTelophone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTextFieldTelophoneFocusGained

    private void jTextFieldTelophoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelophoneFocusLost
        // TODO add your handling code here:
        jTextFieldTelophone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTextFieldTelophoneFocusLost

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        // TODO add your handling code here:
        jTextFieldEmail.setText(" ");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jTextFieldEmailFocusLost
       
    private void jPasswordSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordSignUpFocusGained
        // TODO add your handling code here:
        jPasswordSignUp.setText("");
        jPasswordSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jPasswordSignUpFocusGained

    private void jPasswordSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordSignUpFocusLost
        // TODO add your handling code here:
        jPasswordSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jPasswordSignUpFocusLost

    private void jPasswordConfirmPassSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordConfirmPassSignupFocusGained
        // TODO add your handling code here:
        jPasswordConfirmPassSignup.setText("");
        jPasswordConfirmPassSignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jPasswordConfirmPassSignupFocusGained

    private void jPasswordConfirmPassSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordConfirmPassSignupFocusLost
        // TODO add your handling code here:
        jPasswordConfirmPassSignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jPasswordConfirmPassSignupFocusLost

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // TODO add your handling code here:
        String name;
        String surname;
        String gender;
        Date birthDate;
        String conDisease;
        String email;
        String tel;
        String deptID;
        String oldPass;
        String newPass;
        StringBuffer sb;
        String position;
        
        name = jTfFirstName.getText();
        surname = jTextFieldSurname.getText();
        if(jRadioButtonGenderMale.getDisplayedMnemonicIndex()==-1)
            gender = "male";
        else if(jRadioButtonGenderFemale.getDisplayedMnemonicIndex()==0)
            gender = "female";
        else
            JOptionPane.showMessageDialog(null,"Pleas select gender!","Check Gender",JOptionPane.WARNING_MESSAGE);
        
        birthDate = jDateChooserBirthDate.getDate();
        conDisease = jTextFieldConDisease.getText();
        email = jTextFieldEmail.getText();
        oldPass = jPasswordSignUp.getText();
        newPass = jPasswordConfirmPassSignup.getText();
        password(oldPass,newPass);
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jRadioButtonGenderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGenderMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGenderMaleActionPerformed

    private void jRadioButtonGenderMaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonGenderMaleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGenderMaleFocusGained

     public String password(String oldPass,String newPass){//พาสเวิร์ดที่ user ใส่มาสองรอบต้องเป็นตัวเดียวกัน
         String password="";
        if(oldPass==newPass){
           password = newPass;
        }else{
           JOptionPane.showMessageDialog(null,"These passwords don't match. Try again?","Check Password",JOptionPane.WARNING_MESSAGE); 
//           jPasswordConfirmPassSignup.JComponent.AccessibleJComponent.AccessibleFocusHandler.focusGained(FocusEvent event){;
        }
        return password;
    }
        
//        jTFSearch.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTFSearchActionPerformed(evt);
//            }
//        });
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private com.toedter.calendar.JDateChooser jDateChooserBirthDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStarLN;
    private javax.swing.JLabel jLbConfirmPassWord;
    private javax.swing.JLabel jLbCongenitialDisease;
    private javax.swing.JLabel jLbDateOfBirth;
    private javax.swing.JLabel jLbEmail;
    private javax.swing.JLabel jLbFirstName;
    private javax.swing.JLabel jLbGender;
    private javax.swing.JLabel jLbId;
    private javax.swing.JLabel jLbLastName;
    private javax.swing.JLabel jLbPassWord;
    private javax.swing.JLabel jLbPosition;
    private javax.swing.JLabel jLbSignUp;
    private javax.swing.JLabel jLbStarBirthDay;
    private javax.swing.JLabel jLbStarConfirmPass;
    private javax.swing.JLabel jLbStarEmail;
    private javax.swing.JLabel jLbStarFirstName;
    private javax.swing.JLabel jLbStarGender;
    private javax.swing.JLabel jLbStarId;
    private javax.swing.JLabel jLbStarPassword;
    private javax.swing.JLabel jLbStarPosition;
    private javax.swing.JLabel jLbStarTelophone;
    private javax.swing.JLabel jLbTelophone;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPasswordField jPasswordConfirmPassSignup;
    private javax.swing.JPasswordField jPasswordSignUp;
    private javax.swing.JRadioButton jRadioButtonGenderFemale;
    private javax.swing.JRadioButton jRadioButtonGenderMale;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldConDisease;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTelophone;
    private javax.swing.JTextField jTfFirstName;
    // End of variables declaration//GEN-END:variables
}
