package bike_gui;

import bike.*;
import java.awt.Color;
import java.awt.Point;
import javax.swing.*;

public class BikeAdmin extends javax.swing.JFrame {

    private Sharing sh = new Sharing();

    public BikeAdmin() {
        initComponents();
        cpPage.setVisible(false);
        sharingPage.setVisible(false);
        titleSignout.setVisible(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioSharing = new javax.swing.ButtonGroup();
        mainAdmin = new javax.swing.JPanel();
        barSearch = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        iconSearch = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        backMenuBar = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        news = new javax.swing.JLabel();
        bikeRepair = new javax.swing.JLabel();
        canCounter = new javax.swing.JLabel();
        bikeSharing = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        titleSignout = new javax.swing.JLabel();
        arrowDownIcon = new javax.swing.JLabel();
        barUser = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        backBarUser = new javax.swing.JPanel();
        backBarIcon = new javax.swing.JPanel();
        barIcon = new javax.swing.JPanel();
        iconMenu = new javax.swing.JLabel();
        iconBike = new javax.swing.JLabel();
        iconProfile = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        barNoti = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        iconNoti = new javax.swing.JLabel();
        cpPage = new javax.swing.JPanel();
        titleCountCan = new javax.swing.JLabel();
        titleNameUser = new javax.swing.JLabel();
        s3 = new javax.swing.JSeparator();
        s4 = new javax.swing.JSeparator();
        nameOfUser = new javax.swing.JTextField();
        countOfCan = new javax.swing.JTextField();
        submitBut = new javax.swing.JButton();
        cancleAdminBut = new javax.swing.JButton();
        titleLastname = new javax.swing.JLabel();
        surnameOfUser = new javax.swing.JTextField();
        s5 = new javax.swing.JSeparator();
        sharingPage = new javax.swing.JPanel();
        menuSharing = new javax.swing.JPanel();
        menuAdd = new javax.swing.JButton();
        menuEdit = new javax.swing.JButton();
        menuDelete = new javax.swing.JButton();
        backAdd = new javax.swing.JPanel();
        backEdit = new javax.swing.JPanel();
        backDelete = new javax.swing.JPanel();
        sharingPageTab = new javax.swing.JPanel();
        layerAddItem = new javax.swing.JPanel();
        titleItemId = new javax.swing.JLabel();
        s6 = new javax.swing.JSeparator();
        s7 = new javax.swing.JSeparator();
        titleItemName = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        titleItemCount = new javax.swing.JLabel();
        s8 = new javax.swing.JSeparator();
        itemAmount = new javax.swing.JTextField();
        submitButSharing = new javax.swing.JButton();
        cancleButSharing = new javax.swing.JButton();
        itemId = new javax.swing.JTextField();
        notiSharing = new javax.swing.JLabel();
        itemList = new javax.swing.JButton();
        itemListScroll = new javax.swing.JScrollPane();
        itemListPage = new javax.swing.JPanel();
        titleItemList = new javax.swing.JLabel();
        closeBut = new javax.swing.JLabel();
        titleWhat = new javax.swing.JLabel();
        radioType = new javax.swing.JRadioButton();
        radioEquip = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barSearch.setBackground(new java.awt.Color(13, 24, 35));
        barSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        barSearch.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 120, 40));

        iconSearch.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        iconSearch.setForeground(new java.awt.Color(255, 255, 255));
        iconSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/magnifying-glass.png"))); // NOI18N
        iconSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSearchMouseClicked(evt);
            }
        });
        barSearch.add(iconSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 50, 50));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Leelawadee", 0, 30)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("GREEN  SOCIETY");
        title.setToolTipText("");
        barSearch.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        search.setBackground(new java.awt.Color(13, 24, 35));
        search.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(null);
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        barSearch.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 120, 30));

        mainAdmin.add(barSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 900, 60));

        backMenuBar.setBackground(new java.awt.Color(22, 31, 39));
        backMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar.setBackground(new java.awt.Color(13, 24, 35));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        news.setBackground(new java.awt.Color(0, 0, 0));
        news.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        news.setForeground(new java.awt.Color(255, 255, 255));
        news.setText("     News");
        news.setToolTipText("");
        news.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menuBar.add(news, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 20));

        bikeRepair.setBackground(new java.awt.Color(0, 0, 0));
        bikeRepair.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        bikeRepair.setForeground(new java.awt.Color(255, 255, 255));
        bikeRepair.setText("     Bike Repairing");
        bikeRepair.setToolTipText("");
        bikeRepair.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menuBar.add(bikeRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 20));

        canCounter.setBackground(new java.awt.Color(0, 0, 0));
        canCounter.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        canCounter.setForeground(new java.awt.Color(255, 255, 255));
        canCounter.setText("     Can Counter");
        canCounter.setToolTipText("");
        canCounter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        canCounter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canCounterMouseClicked(evt);
            }
        });
        menuBar.add(canCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 140, 20));

        bikeSharing.setBackground(new java.awt.Color(255, 255, 255));
        bikeSharing.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        bikeSharing.setForeground(new java.awt.Color(255, 255, 255));
        bikeSharing.setText("     Bike Sharing");
        bikeSharing.setToolTipText("");
        bikeSharing.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bikeSharing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bikeSharingMouseClicked(evt);
            }
        });
        menuBar.add(bikeSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 20));

        history.setBackground(new java.awt.Color(0, 0, 0));
        history.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setText("     History");
        history.setToolTipText("");
        history.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menuBar.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 20));

        profile.setBackground(new java.awt.Color(0, 0, 0));
        profile.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("     PROFILE");
        profile.setToolTipText("");
        menuBar.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 140, 30));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("MENU");
        menu.setToolTipText("");
        menuBar.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 30));

        timer.setBackground(new java.awt.Color(0, 0, 0));
        timer.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        timer.setForeground(new java.awt.Color(255, 255, 255));
        timer.setText("     Timer");
        timer.setToolTipText("");
        timer.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        timer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timerMouseClicked(evt);
            }
        });
        menuBar.add(timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 20));

        support.setBackground(new java.awt.Color(0, 0, 0));
        support.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("     Support");
        support.setToolTipText("");
        support.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menuBar.add(support, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 140, 20));

        titleSignout.setBackground(new java.awt.Color(0, 0, 0));
        titleSignout.setFont(new java.awt.Font("Leelawadee", 0, 13)); // NOI18N
        titleSignout.setForeground(new java.awt.Color(255, 255, 255));
        titleSignout.setText("     SIGN OUT");
        titleSignout.setToolTipText("");
        menuBar.add(titleSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 140, 30));

        arrowDownIcon.setBackground(new java.awt.Color(0, 0, 0));
        arrowDownIcon.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        arrowDownIcon.setForeground(new java.awt.Color(255, 255, 255));
        arrowDownIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowDownIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/chevron-arrow-down.png"))); // NOI18N
        arrowDownIcon.setToolTipText("");
        menuBar.add(arrowDownIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, 30));

        backMenuBar.add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        mainAdmin.add(backMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 480));

        barUser.setBackground(new java.awt.Color(19, 175, 248));
        barUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/man.png"))); // NOI18N
        barUser.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(13, 24, 35));
        name.setText("NAME  SURNAME");
        name.setToolTipText("");
        name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        barUser.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 50));

        position.setBackground(new java.awt.Color(0, 0, 0));
        position.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        position.setForeground(new java.awt.Color(255, 255, 255));
        position.setText("Student");
        position.setToolTipText("");
        position.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        barUser.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, 50));

        mainAdmin.add(barUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 200, 60));

        backBarUser.setBackground(new java.awt.Color(55, 200, 255));
        backBarUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainAdmin.add(backBarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 60));

        backBarIcon.setBackground(new java.awt.Color(55, 200, 255));
        backBarIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barIcon.setBackground(new java.awt.Color(19, 175, 248));
        barIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/menu.png"))); // NOI18N
        barIcon.add(iconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 30));

        iconBike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/bike.png"))); // NOI18N
        barIcon.add(iconBike, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        iconProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/profile-user.png"))); // NOI18N
        barIcon.add(iconProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 50, 50));

        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/signout.png"))); // NOI18N
        signout.setContentAreaFilled(false);
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signoutMouseExited(evt);
            }
        });
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        barIcon.add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 50, 50));

        backBarIcon.add(barIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 540));

        mainAdmin.add(backBarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 540));

        barNoti.setBackground(new java.awt.Color(13, 24, 35));
        barNoti.setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(55, 200, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barNoti.add(jSeparator1);
        jSeparator1.setBounds(60, 0, 20, 66);

        iconNoti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconNoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/notifications-button.png"))); // NOI18N
        barNoti.add(iconNoti);
        iconNoti.setBounds(0, 0, 60, 60);

        mainAdmin.add(barNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 770, 60));

        cpPage.setBackground(new java.awt.Color(25, 41, 65));
        cpPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleCountCan.setFont(new java.awt.Font("Leelawadee", 0, 20)); // NOI18N
        titleCountCan.setForeground(new java.awt.Color(255, 255, 255));
        titleCountCan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCountCan.setText("Count of Can :");
        cpPage.add(titleCountCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 40));

        titleNameUser.setFont(new java.awt.Font("Leelawadee", 0, 20)); // NOI18N
        titleNameUser.setForeground(new java.awt.Color(255, 255, 255));
        titleNameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNameUser.setText("Firstname User :");
        cpPage.add(titleNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 60));

        s3.setForeground(new java.awt.Color(255, 255, 255));
        cpPage.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 240, 10));

        s4.setForeground(new java.awt.Color(255, 255, 255));
        cpPage.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 240, 10));

        nameOfUser.setBackground(new java.awt.Color(25, 41, 65));
        nameOfUser.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        nameOfUser.setForeground(new java.awt.Color(153, 153, 153));
        nameOfUser.setText("    Name");
        nameOfUser.setBorder(null);
        nameOfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameOfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameOfUserFocusLost(evt);
            }
        });
        cpPage.add(nameOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 230, 30));

        countOfCan.setBackground(new java.awt.Color(25, 41, 65));
        countOfCan.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        countOfCan.setForeground(new java.awt.Color(153, 153, 153));
        countOfCan.setText("    Count");
        countOfCan.setBorder(null);
        countOfCan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countOfCanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countOfCanFocusLost(evt);
            }
        });
        cpPage.add(countOfCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 240, 30));

        submitBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submit.png"))); // NOI18N
        submitBut.setContentAreaFilled(false);
        submitBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitButMouseExited(evt);
            }
        });
        submitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButActionPerformed(evt);
            }
        });
        cpPage.add(submitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, -1));

        cancleAdminBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleBut.png"))); // NOI18N
        cancleAdminBut.setContentAreaFilled(false);
        cancleAdminBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancleAdminButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancleAdminButMouseExited(evt);
            }
        });
        cancleAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleAdminButActionPerformed(evt);
            }
        });
        cpPage.add(cancleAdminBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 160, -1));

        titleLastname.setFont(new java.awt.Font("Leelawadee", 0, 20)); // NOI18N
        titleLastname.setForeground(new java.awt.Color(255, 255, 255));
        titleLastname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLastname.setText("Lastname User :");
        cpPage.add(titleLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 60));

        surnameOfUser.setBackground(new java.awt.Color(25, 41, 65));
        surnameOfUser.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        surnameOfUser.setForeground(new java.awt.Color(153, 153, 153));
        surnameOfUser.setText("    Surname");
        surnameOfUser.setBorder(null);
        surnameOfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameOfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                surnameOfUserFocusLost(evt);
            }
        });
        cpPage.add(surnameOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, 30));

        s5.setForeground(new java.awt.Color(255, 255, 255));
        cpPage.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 240, 10));

        mainAdmin.add(cpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 421));

        sharingPage.setBackground(new java.awt.Color(25, 41, 65));
        sharingPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuSharing.setBackground(new java.awt.Color(13, 24, 35));
        menuSharing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuAdd.setBackground(new java.awt.Color(13, 24, 35));
        menuAdd.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        menuAdd.setForeground(new java.awt.Color(102, 102, 102));
        menuAdd.setText("Add Item");
        menuAdd.setToolTipText("");
        menuAdd.setContentAreaFilled(false);
        menuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddActionPerformed(evt);
            }
        });
        menuSharing.add(menuAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 50));

        menuEdit.setBackground(new java.awt.Color(13, 24, 35));
        menuEdit.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        menuEdit.setForeground(new java.awt.Color(102, 102, 102));
        menuEdit.setText("Edit Item");
        menuEdit.setToolTipText("");
        menuEdit.setContentAreaFilled(false);
        menuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditActionPerformed(evt);
            }
        });
        menuSharing.add(menuEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 10, 120, 50));

        menuDelete.setBackground(new java.awt.Color(25, 41, 65));
        menuDelete.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        menuDelete.setForeground(new java.awt.Color(102, 102, 102));
        menuDelete.setText("Delete Item");
        menuDelete.setToolTipText("");
        menuDelete.setContentAreaFilled(false);
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuSharing.add(menuDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 50));

        backAdd.setBackground(new java.awt.Color(25, 41, 65));

        javax.swing.GroupLayout backAddLayout = new javax.swing.GroupLayout(backAdd);
        backAdd.setLayout(backAddLayout);
        backAddLayout.setHorizontalGroup(
            backAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        backAddLayout.setVerticalGroup(
            backAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        menuSharing.add(backAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, -1));

        backEdit.setBackground(new java.awt.Color(25, 41, 65));

        javax.swing.GroupLayout backEditLayout = new javax.swing.GroupLayout(backEdit);
        backEdit.setLayout(backEditLayout);
        backEditLayout.setHorizontalGroup(
            backEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        backEditLayout.setVerticalGroup(
            backEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        menuSharing.add(backEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 130, -1));

        backDelete.setBackground(new java.awt.Color(25, 41, 65));

        javax.swing.GroupLayout backDeleteLayout = new javax.swing.GroupLayout(backDelete);
        backDelete.setLayout(backDeleteLayout);
        backDeleteLayout.setHorizontalGroup(
            backDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        backDeleteLayout.setVerticalGroup(
            backDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        menuSharing.add(backDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, -1));

        sharingPage.add(menuSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        sharingPageTab.setBackground(new java.awt.Color(25, 41, 65));
        sharingPageTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layerAddItem.setBackground(new java.awt.Color(13, 24, 35));
        layerAddItem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add Item", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee", 0, 20), new java.awt.Color(3, 153, 223))); // NOI18N
        layerAddItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleItemId.setBackground(new java.awt.Color(255, 255, 255));
        titleItemId.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        titleItemId.setForeground(new java.awt.Color(255, 255, 255));
        titleItemId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleItemId.setText("Item ID :");
        layerAddItem.add(titleItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 40));
        layerAddItem.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 10));
        layerAddItem.add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, 10));

        titleItemName.setBackground(new java.awt.Color(255, 255, 255));
        titleItemName.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        titleItemName.setForeground(new java.awt.Color(255, 255, 255));
        titleItemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleItemName.setText("Item Name :");
        layerAddItem.add(titleItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        itemName.setBackground(new java.awt.Color(13, 24, 35));
        itemName.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        itemName.setForeground(new java.awt.Color(153, 153, 153));
        itemName.setText("Name");
        itemName.setBorder(null);
        itemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNameFocusLost(evt);
            }
        });
        layerAddItem.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 30));

        titleItemCount.setBackground(new java.awt.Color(255, 255, 255));
        titleItemCount.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        titleItemCount.setForeground(new java.awt.Color(255, 255, 255));
        titleItemCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleItemCount.setText("Item Amount :");
        layerAddItem.add(titleItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));
        layerAddItem.add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 20));

        itemAmount.setBackground(new java.awt.Color(13, 24, 35));
        itemAmount.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        itemAmount.setForeground(new java.awt.Color(153, 153, 153));
        itemAmount.setText("Count");
        itemAmount.setBorder(null);
        itemAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemAmountFocusLost(evt);
            }
        });
        layerAddItem.add(itemAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, 30));

        submitButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submitMini.png"))); // NOI18N
        submitButSharing.setContentAreaFilled(false);
        submitButSharing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButSharingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitButSharingMouseExited(evt);
            }
        });
        submitButSharing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButSharingActionPerformed(evt);
            }
        });
        layerAddItem.add(submitButSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        cancleButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleMini.png"))); // NOI18N
        cancleButSharing.setContentAreaFilled(false);
        cancleButSharing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancleButSharingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancleButSharingMouseExited(evt);
            }
        });
        cancleButSharing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButSharingActionPerformed(evt);
            }
        });
        layerAddItem.add(cancleButSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, 40));

        itemId.setEditable(false);
        itemId.setBackground(new java.awt.Color(13, 24, 35));
        itemId.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        itemId.setForeground(new java.awt.Color(153, 153, 153));
        itemId.setText("ID");
        itemId.setBorder(null);
        itemId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemIdFocusLost(evt);
            }
        });
        layerAddItem.add(itemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 30));

        notiSharing.setBackground(new java.awt.Color(13, 24, 35));
        notiSharing.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        notiSharing.setForeground(new java.awt.Color(130, 255, 134));
        notiSharing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notiSharing.setText("Success!!!");
        notiSharing.setToolTipText("");
        layerAddItem.add(notiSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 30));

        itemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/itemList.png"))); // NOI18N
        itemList.setToolTipText("Item List");
        itemList.setContentAreaFilled(false);
        itemList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemListMouseExited(evt);
            }
        });
        itemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListActionPerformed(evt);
            }
        });
        layerAddItem.add(itemList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 50, -1));

        sharingPageTab.add(layerAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 350, 270));

        itemListScroll.setBackground(new java.awt.Color(13, 24, 35));
        itemListScroll.setBorder(null);

        itemListPage.setBackground(new java.awt.Color(13, 24, 35));
        itemListPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleItemList.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        titleItemList.setForeground(new java.awt.Color(255, 255, 255));
        titleItemList.setText("Item List");
        itemListPage.add(titleItemList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 60));

        closeBut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/delete-button.png"))); // NOI18N
        closeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButMouseClicked(evt);
            }
        });
        itemListPage.add(closeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 50, 40));

        itemListScroll.setViewportView(itemListPage);

        sharingPageTab.add(itemListScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 330));

        titleWhat.setBackground(new java.awt.Color(255, 255, 255));
        titleWhat.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        titleWhat.setForeground(new java.awt.Color(255, 255, 255));
        titleWhat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleWhat.setText("What item do you want to ___? ");
        sharingPageTab.add(titleWhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 50));

        radioType.setBackground(new java.awt.Color(25, 41, 65));
        radioType.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        radioType.setForeground(new java.awt.Color(19, 175, 248));
        radioType.setText("Type Bicycle");
        radioType.setBorder(null);
        radioType.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        radioType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTypeActionPerformed(evt);
            }
        });
        sharingPageTab.add(radioType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 40));

        radioEquip.setBackground(new java.awt.Color(25, 41, 65));
        radioEquip.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        radioEquip.setForeground(new java.awt.Color(19, 175, 248));
        radioEquip.setText("Equipment");
        radioEquip.setBorder(null);
        radioEquip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioEquip.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        radioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEquipActionPerformed(evt);
            }
        });
        sharingPageTab.add(radioEquip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, 40));

        sharingPage.add(sharingPageTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 770, 360));

        mainAdmin.add(sharingPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 421));

        getContentPane().add(mainAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSearchMouseClicked
        search.requestFocusInWindow();

    }//GEN-LAST:event_iconSearchMouseClicked

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if (search.getText().equals("Search")) {
            search.setText("");
        }
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if (search.getText().equals("") || search.getText().length() == 0) {
            search.setText("Search");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if (search.getText().equals("") || search.getText().length() == 0) {
            search.setText("Search");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void canCounterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canCounterMouseClicked
        canCounter.setForeground(new java.awt.Color(19, 175, 248));
        cpPage.setVisible(true);
        nameOfUser.setText("    Name");
        surnameOfUser.setText("    Surname");
        countOfCan.setText("    Count");
        nameOfUser.setForeground(new Color(153, 153, 153, 150));
        surnameOfUser.setForeground(new Color(153, 153, 153, 150));
        countOfCan.setForeground(new Color(153, 153, 153, 150));
        bikeSharing.setForeground(new java.awt.Color(255, 255, 255));
        sharingPage.setVisible(false);
    }//GEN-LAST:event_canCounterMouseClicked

    private void bikeSharingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bikeSharingMouseClicked
        bikeSharing.setForeground(new java.awt.Color(19, 175, 248));
        menuAdd.setForeground(new Color(102, 102, 102));
        menuEdit.setForeground(new Color(102, 102, 102));
        menuDelete.setForeground(new Color(102, 102, 102));
        sharingPage.setVisible(true);
        menuSharing.setVisible(true);
        backAdd.setVisible(false);
        backEdit.setVisible(false);
        backDelete.setVisible(false);
        sharingPageTab.setVisible(false);
        radioType.setSelected(false);
        radioEquip.setSelected(false);
        layerAddItem.setVisible(false);
        canCounter.setForeground(new java.awt.Color(255, 255, 255));
        cpPage.setVisible(false);
        itemListScroll.setVisible(false);
        sh.selectAllItemID();
    }//GEN-LAST:event_bikeSharingMouseClicked

    private void timerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timerMouseClicked

    }//GEN-LAST:event_timerMouseClicked

    private void nameOfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameOfUserFocusLost
        if (nameOfUser.getText().equals("") || nameOfUser.getText().length() == 0) {
            nameOfUser.setForeground(new Color(153, 153, 153, 150));
            nameOfUser.setText("    Name");
        }
    }//GEN-LAST:event_nameOfUserFocusLost

    private void countOfCanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countOfCanFocusLost
        if (countOfCan.getText().equals("") || countOfCan.getText().length() == 0) {
            countOfCan.setForeground(new Color(153, 153, 153, 150));
            countOfCan.setText("    Count");
        }
    }//GEN-LAST:event_countOfCanFocusLost

    private void nameOfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameOfUserFocusGained
        if (nameOfUser.getText().equals("    Name")) {
            nameOfUser.setForeground(new Color(255, 255, 255));
            nameOfUser.setText("");
        }
    }//GEN-LAST:event_nameOfUserFocusGained

    private void countOfCanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countOfCanFocusGained
        if (countOfCan.getText().equals("    Count")) {
            countOfCan.setForeground(new Color(255, 255, 255));
            countOfCan.setText("");
        }
    }//GEN-LAST:event_countOfCanFocusGained

    private void submitButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButMouseEntered
        submitBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submitClick.png")));
    }//GEN-LAST:event_submitButMouseEntered
    private void submitButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButMouseExited
        submitBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submit.png")));
    }//GEN-LAST:event_submitButMouseExited

    private void cancleAdminButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleAdminButMouseEntered
        cancleAdminBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleOvalClick.png")));
    }//GEN-LAST:event_cancleAdminButMouseEntered

    private void cancleAdminButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleAdminButMouseExited
        cancleAdminBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleOval.png")));
    }//GEN-LAST:event_cancleAdminButMouseExited

    private void submitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButActionPerformed
        String name = nameOfUser.getText();
        String surname = surnameOfUser.getText();
        String can = countOfCan.getText();
        if (name.equals("    Name") || surname.equals("    Surname")) {
            JOptionPane.showMessageDialog(this, "Please EnterName and Surname", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int c = Integer.parseInt(can);
                sh.getCp().increseCp(name, surname, c);
                JOptionPane.showMessageDialog(this, "Success", "Success", JOptionPane.INFORMATION_MESSAGE);
                nameOfUser.setForeground(new Color(153, 153, 153, 150));
                nameOfUser.setText("    Name");
                countOfCan.setForeground(new Color(153, 153, 153, 150));
                countOfCan.setText("    Count");
                surnameOfUser.setForeground(new Color(153, 153, 153, 150));
                surnameOfUser.setText("    Surname");
            } catch (SelectMemberNameException smn) {
                JOptionPane.showMessageDialog(this, smn.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ne) {
                JOptionPane.showMessageDialog(this, "Can of Count not correct, Please enter again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_submitButActionPerformed

    private void cancleAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleAdminButActionPerformed
        nameOfUser.setForeground(new Color(153, 153, 153, 150));
        nameOfUser.setText("    Name");
        countOfCan.setForeground(new Color(153, 153, 153, 150));
        countOfCan.setText("    Count");
        surnameOfUser.setForeground(new Color(153, 153, 153, 150));
        surnameOfUser.setText("    Surname");
    }//GEN-LAST:event_cancleAdminButActionPerformed

    private void surnameOfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameOfUserFocusGained
        if (surnameOfUser.getText().equals("    Surname")) {
            surnameOfUser.setForeground(new Color(255, 255, 255));
            surnameOfUser.setText("");
        }
    }//GEN-LAST:event_surnameOfUserFocusGained

    private void surnameOfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameOfUserFocusLost
        if (surnameOfUser.getText().equals("") || surnameOfUser.getText().length() == 0) {
            surnameOfUser.setForeground(new Color(153, 153, 153, 150));
            surnameOfUser.setText("    Surname");
        }
    }//GEN-LAST:event_surnameOfUserFocusLost

    private void radioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEquipActionPerformed
        layerAddItem.setVisible(true);
        radioType.setSelected(false);
        if (backAdd.isVisible()) {
            itemId.setText(sh.selectItemIdEquip());
            itemId.setEditable(false);
            notiSharing.setVisible(false);
            titleItemName.setVisible(true);
            itemName.setVisible(true);
            titleItemCount.setVisible(true);
            itemAmount.setVisible(true);
            s7.setVisible(true);
            s8.setVisible(true);
            itemList.setVisible(false);
        }
    }//GEN-LAST:event_radioEquipActionPerformed

    private void radioTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTypeActionPerformed
        layerAddItem.setVisible(true);
        radioEquip.setSelected(false);
        if (backAdd.isVisible()) {
            itemId.setText(sh.selectItemIdBike());
            itemId.setEditable(false);
            notiSharing.setVisible(false);
            titleItemName.setVisible(true);
            itemName.setVisible(true);
            titleItemCount.setVisible(true);
            itemAmount.setVisible(true);
            s7.setVisible(true);
            s8.setVisible(true);
            itemList.setVisible(false);
        }
    }//GEN-LAST:event_radioTypeActionPerformed

    private void closeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButMouseClicked
        itemListScroll.setVisible(false);
        layerAddItem.setVisible(true);
    }//GEN-LAST:event_closeButMouseClicked

    private void itemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListActionPerformed
        itemListScroll.setVisible(true);
        layerAddItem.setVisible(false);
        itemListScroll.getViewport().setViewPosition(new Point(0, 0));
        int y = 70;
        String all[] = sh.selectAllAdmin();
        JPanel[] jp = new JPanel[all.length];
        JLabel[] detail = new JLabel[all.length];
        for (int i = 0; i < all.length; i++) {
            jp[i] = new JPanel();
            jp[i].setBackground(new Color(102, 102, 102));
            jp[i].setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            detail[i] = new JLabel();
            detail[i].setFont(new java.awt.Font("Leelawadee", 0, 18));
            detail[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            detail[i].setText(all[i]);

            jp[i].add(detail[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 580, 30));
            itemListPage.add(jp[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(40, y, 600, 50));
            y += 70;
        }
        itemListScroll.setViewportView(itemListPage);
    }//GEN-LAST:event_itemListActionPerformed

    private void itemListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListMouseExited
        itemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/itemList.png")));
    }//GEN-LAST:event_itemListMouseExited

    private void itemListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListMouseEntered
        itemList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/itemListClick.png")));
    }//GEN-LAST:event_itemListMouseEntered

    private void itemIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIdFocusLost
        if (itemId.getText().equals("") || itemId.getText().length() == 0) {
            itemId.setForeground(new Color(153, 153, 153, 150));
            itemId.setText("ID");
        }
    }//GEN-LAST:event_itemIdFocusLost

    private void itemIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIdFocusGained
        if (itemId.getText().equals("ID")) {
            itemId.setForeground(new Color(255, 255, 255));
            itemId.setText("");
        }
    }//GEN-LAST:event_itemIdFocusGained

    private void cancleButSharingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButSharingActionPerformed
        itemId.setForeground(new Color(153, 153, 153, 150));
        itemId.setText("ID");
        itemName.setForeground(new Color(153, 153, 153, 150));
        itemName.setText("Name");
        itemAmount.setForeground(new Color(153, 153, 153, 150));
        itemAmount.setText("Count");
        titleItemName.setForeground(new Color(255, 255, 255));
        titleItemCount.setForeground(new Color(255, 255, 255));
        titleItemId.setForeground(new Color(255, 255, 255));
        notiSharing.setVisible(false);
        if (backAdd.isVisible()) {
            radioType.setSelected(false);
            radioEquip.setSelected(false);
            layerAddItem.setVisible(false);
        } else if (backEdit.isVisible()) {
            layerAddItem.setVisible(true);
        } else if (backEdit.isVisible()) {
            layerAddItem.setVisible(true);
        }
    }//GEN-LAST:event_cancleButSharingActionPerformed

    private void cancleButSharingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleButSharingMouseExited
        cancleButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleMini.png")));
    }//GEN-LAST:event_cancleButSharingMouseExited

    private void cancleButSharingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleButSharingMouseEntered
        cancleButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/cancleMiniClick.png")));
    }//GEN-LAST:event_cancleButSharingMouseEntered

    private void submitButSharingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButSharingActionPerformed
        if (backAdd.isVisible()) {
            String id = itemId.getText();
            String name = itemName.getText();
            titleItemName.setForeground(new Color(255, 255, 255));
            titleItemCount.setForeground(new Color(255, 255, 255));
            try {
                int count = Integer.parseInt(itemAmount.getText());
                if (name.equals("Name")) {
                    titleItemName.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else {
                    sh.addItem(id, name, count);
                    notiSharing.setText("Success.");
                    notiSharing.setForeground(new Color(130, 255, 134));
                    notiSharing.setVisible(true);
                    itemId.setForeground(new Color(153, 153, 153, 150));
                    itemId.setText("ID");
                    itemName.setForeground(new Color(153, 153, 153, 150));
                    itemName.setText("Name");
                    itemAmount.setForeground(new Color(153, 153, 153, 150));
                    itemAmount.setText("Count");
                }
            } catch (NumberFormatException ne) {
                if (name.equals("Name")) {
                    titleItemName.setForeground(new Color(255, 51, 51));
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else {
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                }
            }

        } else if (backEdit.isVisible()) {
            boolean check = false;
            String id = itemId.getText();
            String allId[] = sh.getItemID();
            for (int i = 0; i < allId.length; i++) {
                if (id.equals(allId[i])) {
                    check = true;
                }
            }
            String name = itemName.getText();
            titleItemName.setForeground(new Color(255, 255, 255));
            titleItemCount.setForeground(new Color(255, 255, 255));
            titleItemId.setForeground(new Color(255, 255, 255));

            try {
                int count = Integer.parseInt(itemAmount.getText());
                if (check == false && name.equals("Name")) {
                    titleItemId.setForeground(new Color(255, 51, 51));
                    titleItemName.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else if (name.equals("Name") && check == true) {
                    titleItemName.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else if (check == false) {
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                    titleItemId.setForeground(new Color(255, 51, 51));
                } else {
                    sh.editItem(id, name, count);
                    notiSharing.setText("Success.");
                    notiSharing.setForeground(new Color(130, 255, 134));
                    notiSharing.setVisible(true);
                    itemId.setForeground(new Color(153, 153, 153, 150));
                    itemId.setText("ID");
                    itemName.setForeground(new Color(153, 153, 153, 150));
                    itemName.setText("Name");
                    itemAmount.setForeground(new Color(153, 153, 153, 150));
                    itemAmount.setText("Count");
                }
            } catch (NumberFormatException ne) {
                if (check == false && name.equals("Name")) {
                    titleItemId.setForeground(new Color(255, 51, 51));
                    titleItemName.setForeground(new Color(255, 51, 51));
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else if (name.equals("Name") && check == true) {
                    titleItemName.setForeground(new Color(255, 51, 51));
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else if (check == false) {
                    titleItemId.setForeground(new Color(255, 51, 51));
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                } else {
                    titleItemCount.setForeground(new Color(255, 51, 51));
                    notiSharing.setText("Not Success,Please enter again");
                    notiSharing.setForeground(new Color(255, 51, 51));
                    notiSharing.setVisible(true);
                }
            }

        } else if (backDelete.isVisible()) {
            boolean check = false;
            titleItemId.setForeground(new Color(255, 255, 255));
            String id = itemId.getText();
            String allId[] = sh.getItemID();
            for (int i = 0; i < allId.length; i++) {
                if (id.equals(allId[i])) {
                    check = true;
                }
            }
            if (check == true) {
                sh.deleteItem(id);
            } else if (check == false) {
                notiSharing.setText("Not Success,Please enter again");
                notiSharing.setForeground(new Color(255, 51, 51));
                notiSharing.setVisible(true);
                titleItemId.setForeground(new Color(255, 51, 51));
            }

        }
    }//GEN-LAST:event_submitButSharingActionPerformed

    private void submitButSharingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButSharingMouseExited
        submitButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submitMini.png")));
    }//GEN-LAST:event_submitButSharingMouseExited

    private void submitButSharingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButSharingMouseEntered
        submitButSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/picture/submitMiniClick.png")));
    }//GEN-LAST:event_submitButSharingMouseEntered

    private void itemAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemAmountFocusLost
        if (itemAmount.getText().equals("") || itemAmount.getText().length() == 0) {
            itemAmount.setForeground(new Color(153, 153, 153, 150));
            itemAmount.setText("Count");
        }
    }//GEN-LAST:event_itemAmountFocusLost

    private void itemAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemAmountFocusGained
        if (itemAmount.getText().equals("Count")) {
            itemAmount.setForeground(new Color(255, 255, 255));
            itemAmount.setText("");
        }
    }//GEN-LAST:event_itemAmountFocusGained

    private void itemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameFocusLost
        if (itemName.getText().equals("") || itemName.getText().length() == 0) {
            itemName.setForeground(new Color(153, 153, 153, 150));
            itemName.setText("Name");
        }
    }//GEN-LAST:event_itemNameFocusLost

    private void itemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNameFocusGained
        if (itemName.getText().equals("Name")) {
            itemName.setForeground(new Color(255, 255, 255));
            itemName.setText("");
        }
    }//GEN-LAST:event_itemNameFocusGained

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        titleItemName.setForeground(new Color(255, 255, 255));
        titleItemCount.setForeground(new Color(255, 255, 255));
        titleItemId.setForeground(new Color(255, 255, 255));
        menuAdd.setForeground(new Color(102, 102, 102));
        menuEdit.setForeground(new Color(102, 102, 102));
        menuDelete.setForeground(new Color(255, 255, 255));
        backAdd.setVisible(false);
        backEdit.setVisible(false);
        backDelete.setVisible(true);
        sharingPageTab.setVisible(true);
        titleWhat.setText("What's item do you want to delete?");
        radioType.setSelected(false);
        radioEquip.setSelected(false);
        layerAddItem.setVisible(true);
        layerAddItem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Delete Item", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee", 0, 20), new java.awt.Color(3, 153, 223)));
        itemListScroll.setVisible(false);
        notiSharing.setVisible(false);
        itemId.setText("ID");
        itemId.setForeground(new Color(153, 153, 153, 150));
        itemId.setEditable(true);
        itemName.setText("Name");
        itemName.setForeground(new Color(153, 153, 153, 150));
        itemName.setVisible(false);
        itemAmount.setText("Count");
        itemAmount.setForeground(new Color(153, 153, 153, 150));
        itemAmount.setVisible(false);
        itemList.setVisible(true);
        titleItemCount.setVisible(false);
        titleItemName.setVisible(false);
        s7.setVisible(false);
        s8.setVisible(false);
        radioEquip.setVisible(false);
        radioType.setVisible(false);
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditActionPerformed
        titleItemName.setForeground(new Color(255, 255, 255));
        titleItemCount.setForeground(new Color(255, 255, 255));
        titleItemId.setForeground(new Color(255, 255, 255));
        menuAdd.setForeground(new Color(102, 102, 102));
        menuEdit.setForeground(new Color(255, 255, 255));
        menuDelete.setForeground(new Color(102, 102, 102));
        backAdd.setVisible(false);
        backEdit.setVisible(true);
        backDelete.setVisible(false);
        sharingPageTab.setVisible(true);
        titleWhat.setText("What's item do you want to edit?");
        radioType.setSelected(false);
        radioEquip.setSelected(false);
        radioType.setVisible(false);
        radioEquip.setVisible(false);
        layerAddItem.setVisible(true);
        layerAddItem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Edit Item", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee", 0, 20), new java.awt.Color(3, 153, 223)));
        itemListScroll.setVisible(false);
        notiSharing.setVisible(false);
        itemId.setText("ID");
        itemId.setEditable(true);
        itemId.setForeground(new Color(153, 153, 153, 150));
        itemName.setText("Name");
        itemName.setForeground(new Color(153, 153, 153, 150));
        itemName.setVisible(true);
        itemAmount.setText("Count");
        itemAmount.setForeground(new Color(153, 153, 153, 150));
        itemAmount.setVisible(true);
        itemList.setVisible(true);
        titleItemCount.setVisible(true);
        titleItemName.setVisible(true);
        s7.setVisible(true);
        s8.setVisible(true);
    }//GEN-LAST:event_menuEditActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed
        titleItemName.setForeground(new Color(255, 255, 255));
        titleItemCount.setForeground(new Color(255, 255, 255));
        titleItemId.setForeground(new Color(255, 255, 255));
        menuAdd.setForeground(new Color(255, 255, 255));
        menuEdit.setForeground(new Color(102, 102, 102));
        menuDelete.setForeground(new Color(102, 102, 102));
        backAdd.setVisible(true);
        backEdit.setVisible(false);
        backDelete.setVisible(false);
        sharingPageTab.setVisible(true);
        titleWhat.setText("What's item do you want to add?");
        radioType.setSelected(false);
        radioEquip.setSelected(false);
        radioType.setVisible(true);
        radioEquip.setVisible(true);
        layerAddItem.setVisible(false);
        layerAddItem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add Item", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Leelawadee", 0, 20), new java.awt.Color(3, 153, 223)));
        itemListScroll.setVisible(false);
        notiSharing.setVisible(false);
        itemName.setVisible(true);
        itemAmount.setVisible(true);
        titleItemCount.setVisible(true);
        titleItemName.setVisible(true);
        s7.setVisible(true);
        s8.setVisible(true);
    }//GEN-LAST:event_menuAddActionPerformed

    private void signoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseEntered
        titleSignout.setVisible(true);
    }//GEN-LAST:event_signoutMouseEntered

    private void signoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseExited
        titleSignout.setVisible(false);
    }//GEN-LAST:event_signoutMouseExited

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
       int ans = JOptionPane.showConfirmDialog(this, "Do you want to Sign out ?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if (ans == JOptionPane.YES_OPTION) {
           User.setUserId(0);
           User.setOfficeId(null);
           User.setFirstName(null);
           User.setLastName(null);
           User.setGender(null);
           User.setBirthDate(null);
           User.setCongenitialDisease(null);
           User.setEmail(null);
           User.setTel(null);
           User.setDept(null);
           User.setDeptId(null);
           User.setPositon(null);
       }
    }//GEN-LAST:event_signoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BikeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BikeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BikeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BikeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BikeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowDownIcon;
    private javax.swing.JPanel backAdd;
    private javax.swing.JPanel backBarIcon;
    private javax.swing.JPanel backBarUser;
    private javax.swing.JPanel backDelete;
    private javax.swing.JPanel backEdit;
    private javax.swing.JPanel backMenuBar;
    private javax.swing.JPanel barIcon;
    private javax.swing.JPanel barNoti;
    private javax.swing.JPanel barSearch;
    private javax.swing.JPanel barUser;
    private javax.swing.JLabel bikeRepair;
    private javax.swing.JLabel bikeSharing;
    private javax.swing.JLabel canCounter;
    private javax.swing.JButton cancleAdminBut;
    private javax.swing.JButton cancleButSharing;
    private javax.swing.JLabel closeBut;
    private javax.swing.JTextField countOfCan;
    private javax.swing.JPanel cpPage;
    private javax.swing.JLabel history;
    private javax.swing.JLabel iconBike;
    private javax.swing.JLabel iconMenu;
    private javax.swing.JLabel iconNoti;
    private javax.swing.JLabel iconProfile;
    private javax.swing.JLabel iconSearch;
    private javax.swing.JTextField itemAmount;
    private javax.swing.JTextField itemId;
    private javax.swing.JButton itemList;
    private javax.swing.JPanel itemListPage;
    private javax.swing.JScrollPane itemListScroll;
    private javax.swing.JTextField itemName;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel layerAddItem;
    private javax.swing.JPanel mainAdmin;
    private javax.swing.JLabel menu;
    private javax.swing.JButton menuAdd;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton menuDelete;
    private javax.swing.JButton menuEdit;
    private javax.swing.JPanel menuSharing;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameOfUser;
    private javax.swing.JLabel news;
    private javax.swing.JLabel notiSharing;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel position;
    private javax.swing.JLabel profile;
    private javax.swing.JRadioButton radioEquip;
    private javax.swing.ButtonGroup radioSharing;
    private javax.swing.JRadioButton radioType;
    private javax.swing.JSeparator s3;
    private javax.swing.JSeparator s4;
    private javax.swing.JSeparator s5;
    private javax.swing.JSeparator s6;
    private javax.swing.JSeparator s7;
    private javax.swing.JSeparator s8;
    private javax.swing.JTextField search;
    private javax.swing.JPanel sharingPage;
    private javax.swing.JPanel sharingPageTab;
    private javax.swing.JButton signout;
    private javax.swing.JButton submitBut;
    private javax.swing.JButton submitButSharing;
    private javax.swing.JLabel support;
    private javax.swing.JTextField surnameOfUser;
    private javax.swing.JLabel timer;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleCountCan;
    private javax.swing.JLabel titleItemCount;
    private javax.swing.JLabel titleItemId;
    private javax.swing.JLabel titleItemList;
    private javax.swing.JLabel titleItemName;
    private javax.swing.JLabel titleLastname;
    private javax.swing.JLabel titleNameUser;
    private javax.swing.JLabel titleSignout;
    private javax.swing.JLabel titleWhat;
    // End of variables declaration//GEN-END:variables
}
