package bike.gui;
import bike.*;
import java.awt.Color;
import javax.swing.*;
public class News extends javax.swing.JFrame {
    private AdminNews ad = new AdminNews();
    private JPanel content[] = null;
    public News() {
        initComponents();
        jPanel10.setVisible(false);
        setLocationRelativeTo(null);
        jPanel12.setVisible(false);
        
    }
    
    public void showNews(){
        jPanel12.setVisible(true);
        topic.setText("a");
    }
    
    public void layerUser(){
        int y = 20;
        String[] topic = ad.selectTopicNews();
        JPanel[] jp = new JPanel[topic.length];
        JLabel[] label = new JLabel[topic.length];
        JButton[] click = new JButton[topic.length];
        
        for (int i = 0; i < topic.length; i++) {
            jp[i] = new JPanel();
            jp[i].setBackground(new java.awt.Color(204, 204, 204));
            jp[i].setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            
            label[i] = new JLabel();
            label[i].setText(topic[i]);
            jp[i].add(label[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, -1));
            
            
            click[i] = new JButton();
            click[i].setText("View");
            click[i].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showNews();
                }
            });
            
            jp[i].add(click[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, 20));
            jPanel11.add(jp[i],new org.netbeans.lib.awtextra.AbsoluteConstraints(50, y, 500, 40));
            y+=50;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        newsSharingLabel = new javax.swing.JPanel();
        newsLabel = new javax.swing.JLabel();
        newsRepair = new javax.swing.JLabel();
        newsCanCounterLabel = new javax.swing.JLabel();
        newsSharing = new javax.swing.JLabel();
        newsHistoryLabel = new javax.swing.JLabel();
        newsProfileLabel = new javax.swing.JLabel();
        newsTimerLabel = new javax.swing.JLabel();
        newsSupportLabel = new javax.swing.JLabel();
        newsMenuLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        topic = new javax.swing.JLabel();
        deleteNews = new javax.swing.JButton();
        updateNews = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(25, 41, 65));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(13, 24, 35));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(55, 200, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 10, 60));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/circle.png"))); // NOI18N
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -6, 70, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/notifications-button.png"))); // NOI18N
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 730, 60));

        jPanel8.setBackground(new java.awt.Color(13, 24, 35));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SOCIETY");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 50));

        jTextField1.setBackground(new java.awt.Color(13, 24, 35));
        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Search");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 70, 30));
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 120, 40));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Leelawadee", 0, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GREEN");
        jLabel12.setToolTipText("");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 50));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/magnifying-glass.png"))); // NOI18N
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 40, 40));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 860, 60));

        jPanel3.setBackground(new java.awt.Color(19, 175, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 24, 35));
        jLabel4.setText("NAME  SURNAME");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, 50));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/man.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 200, 60));

        jPanel1.setBackground(new java.awt.Color(19, 175, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/bike.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/profile-user.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 50, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/menu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 30));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/bike.png"))); // NOI18N
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 540));

        jPanel4.setBackground(new java.awt.Color(55, 200, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 60));

        jPanel2.setBackground(new java.awt.Color(55, 200, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 540));

        jPanel6.setBackground(new java.awt.Color(22, 31, 39));

        newsSharingLabel.setBackground(new java.awt.Color(13, 24, 35));
        newsSharingLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newsLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsLabel.setText("     News");
        newsLabel.setToolTipText("");
        newsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLabelMouseClicked(evt);
            }
        });
        newsSharingLabel.add(newsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 20));

        newsRepair.setBackground(new java.awt.Color(0, 0, 0));
        newsRepair.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsRepair.setForeground(new java.awt.Color(255, 255, 255));
        newsRepair.setText("     Bike Repairing");
        newsRepair.setToolTipText("");
        newsRepair.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 20));

        newsCanCounterLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsCanCounterLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsCanCounterLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsCanCounterLabel.setText("     Can Counter");
        newsCanCounterLabel.setToolTipText("");
        newsCanCounterLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsCanCounterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 140, 20));

        newsSharing.setBackground(new java.awt.Color(0, 0, 0));
        newsSharing.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsSharing.setForeground(new java.awt.Color(255, 255, 255));
        newsSharing.setText("     Bike Sharing");
        newsSharing.setToolTipText("");
        newsSharing.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsSharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 20));

        newsHistoryLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsHistoryLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsHistoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsHistoryLabel.setText("     History");
        newsHistoryLabel.setToolTipText("");
        newsHistoryLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsHistoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 20));

        newsProfileLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsProfileLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsProfileLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsProfileLabel.setText("     PROFILE");
        newsProfileLabel.setToolTipText("");
        newsSharingLabel.add(newsProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 140, 30));

        newsTimerLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsTimerLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsTimerLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsTimerLabel.setText("     Timer");
        newsTimerLabel.setToolTipText("");
        newsTimerLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 20));

        newsSupportLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsSupportLabel.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        newsSupportLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsSupportLabel.setText("     Support");
        newsSupportLabel.setToolTipText("");
        newsSupportLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newsSharingLabel.add(newsSupportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 140, 20));

        newsMenuLabel.setBackground(new java.awt.Color(0, 0, 0));
        newsMenuLabel.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        newsMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        newsMenuLabel.setText("MENU");
        newsMenuLabel.setToolTipText("");
        newsSharingLabel.add(newsMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 30));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/chevron-arrow-down.png"))); // NOI18N
        jLabel15.setToolTipText("");
        newsSharingLabel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, 30));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/circle_mini.png"))); // NOI18N
        jLabel24.setToolTipText("");
        newsSharingLabel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 40, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addComponent(newsSharingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newsSharingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 480));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/menu.png"))); // NOI18N
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 30));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_gui/bike.png"))); // NOI18N
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        jPanel10.setBackground(new java.awt.Color(25, 41, 65));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(9, 20, 36));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" Topic :");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        topic.setBackground(new java.awt.Color(255, 255, 255));
        topic.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Galaxy S8");
        jPanel12.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, -1));

        deleteNews.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        deleteNews.setText("Delete");
        deleteNews.setToolTipText("");
        jPanel12.add(deleteNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        updateNews.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        updateNews.setText("Update");
        updateNews.setToolTipText("");
        jPanel12.add(updateNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 650, 280));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 400));

        jPanel11.setBackground(new java.awt.Color(11, 24, 43));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel11);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 600, 330));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("News");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        jButton2.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 730, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new InsertNews().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void newsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLabelMouseClicked
       newsLabel.setForeground(new Color(19,175,248));
       jPanel10.setVisible(true);
       layerUser();
    }//GEN-LAST:event_newsLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new News().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteNews;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel newsCanCounterLabel;
    private javax.swing.JLabel newsHistoryLabel;
    private javax.swing.JLabel newsLabel;
    private javax.swing.JLabel newsMenuLabel;
    private javax.swing.JLabel newsProfileLabel;
    private javax.swing.JLabel newsRepair;
    private javax.swing.JLabel newsSharing;
    private javax.swing.JPanel newsSharingLabel;
    private javax.swing.JLabel newsSupportLabel;
    private javax.swing.JLabel newsTimerLabel;
    private javax.swing.JLabel topic;
    private javax.swing.JButton updateNews;
    // End of variables declaration//GEN-END:variables
}
